import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Landing from "@/components/Landing";
import InfoGalery from "@/components/InfoGalery";
import Info from "@/components/Info";
import SliderSection from "@/components/SliderSection";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className="relative">
          <Header />
          <Landing />
          <InfoGalery />
          <Info />
          <SliderSection />
          <Footer />
        </div>
      </main>
    </>
  );
}
