import Head from "next/head";
// import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Landing from "@/components/Landing";
// import InfoGalery from "@/components/InfoGalery";
import Info from "@/components/Info";
// import SliderSection from "@/components/SliderSection";
import Footer from "@/components/Footer";
import { useRef } from "react";

import logo from "../../public/images/landing_logo.png";
import section2Image1 from "../../public/images/section_2_image_1.webp";
import section2Image2 from "../../public/images/section_2_image_2.webp";
import heartBeat from "../../public/images/heart-beat.png";
import bmi from "../../public/images/bmi.png";
import mentalHeath from "../../public/images/mental-health.png";
import section4Image11 from "../../public/images/section_4_image_1.webp";
import section4Image12 from "../../public/images/section_4_image_2.webp";
import section4Image21 from "../../public/images/section_4_image_2.webp";
import section4Image22 from "../../public/images/section_4_image_1.webp";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const DynamicSlider = dynamic(() => import("@/components/SliderSection"), {
  loading: () => <p>loading...</p>,
});
const DynamicInfoGalery = dynamic(() => import("@/components/InfoGalery"), {
  loading: () => <p>loading...</p>,
});

export default function Home() {
  const homeRef = useRef(null);
  const infoRef = useRef(null);
  const benefitRef = useRef(null);
  const slidereRef = useRef(null);
  const headerData = {
    logo: { src: logo, alt: "logo" },
    menus: [
      {
        label: "Home",
        ref: homeRef,
      },
      {
        label: "Info",
        ref: infoRef,
      },
      {
        label: "Benefit",
        ref: benefitRef,
      },
      {
        label: "Comunity",
        ref: slidereRef,
      },
    ],
  };
  const home = {
    title: "running club",
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doe iusmod tempor",
    button: {
      title: "Start Exploring",
      ref: slidereRef,
    },
  };

  const infoGalery = {
    title: "Runnig and Walking",
    description:
      " Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do" +
      "eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros in " +
      "cursus turpis massa tincidunt dui ut. Id semper risus in hendrerit " +
      "gravida rutrum quisque non. Laoreet suspendisse interdum consectetur " +
      "libero id. Vel risus commodo viverra maecenas accumsan lacus vel " +
      "facilisis volutpat. ",
    image1: {
      src: section2Image1,
      alt: "image section 2",
    },
    image2: {
      src: section2Image2,
      alt: "image section 2",
    },
  };
  const dataBenefit = [
    {
      image: heartBeat,
      alt: "heart beat",
      title: "heart beat",
    },
    {
      image: bmi,
      alt: "bmi",
      title: "weight body",
    },
    {
      image: mentalHeath,
      alt: "mental health",
      title: "release strees",
    },
  ];

  const dataSlider = [
    {
      title: "Running On Road",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do" +
        "eiusmod tempor incididunt ut labore et dolore magna aliqua." +
        " Dolor magna eget est lorem ipsum dolor sit amet consectetur." +
        " Iaculis eu non diam phasellus vestibulum. Eleifend quam" +
        " adipiscing vitae proin sagittis nisl rhoncus. Sit amet nisl" +
        " suscipit",
      image1: {
        src: section4Image11,
        alt: "image 1",
      },
      image2: {
        src: section4Image12,
        alt: "image 2",
      },
    },
    {
      title: "Running On Road 2",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do" +
        "eiusmod tempor incididunt ut labore et dolore magna aliqua." +
        " Dolor magna eget est lorem ipsum dolor sit amet consectetur." +
        " Iaculis eu non diam phasellus vestibulum. Eleifend quam" +
        " adipiscing vitae proin sagittis nisl rhoncus. Sit amet nisl" +
        " suscipit",
      image1: {
        src: section4Image21,
        alt: "image 1",
      },
      image2: {
        src: section4Image22,
        alt: "image 2",
      },
    },
  ];

  return (
    <>
      <Head>
        <title>Workout | Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          httpEquiv="Permissions-Policy"
          content="interest-cohort=()"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className="relative">
          <Header id="header" data={headerData} />
          <Landing id={homeRef} data={home} />
          <DynamicInfoGalery id={infoRef} data={infoGalery} />
          <Info id={benefitRef} data={dataBenefit} />
          <DynamicSlider id={slidereRef} data={dataSlider} />
          <Footer />
        </div>
      </main>
    </>
  );
}
